version: "3.9"
services:
  server:
    privileged: true
    build: 
      context: .
      dockerfile: Dockerfile.server
    ports: 
      - 3000:8080
    depends_on:
      - "server"

  redis:
    build: 
      context: .
      dockerfile: Dockerfile.redis
