version: "3.3"

services:
  server:
    build: 
      context: .
      dockerfile: server.Dockerfile
    depends_on:
      - "redis"
    volumes:
      - database:/var/lib/db/
    restart: on-failure

  redis:
    image: redis:alpine
    restart: on-failure

  nginx:
    container_name: 'production-nginx-container'
    image: nginx:latest
    volumes:
      - ./nginx/nginx-prod.conf:/etc/nginx/nginx.conf
      - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/etc/letsencrypt/live/benchmark.parthetic.me/fullchain.pem:/etc/letsencrypt/live/benchmark.parthetic.me/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/benchmark.parthetic.me/privkey.pem:/etc/letsencrypt/live/benchmark.parthetic.me/privkey.pem
      - /etc/apache2/.htpasswd:/etc/apache2/.htpasswd
      #for certbot challenges
      - ./nginx/html:/usr/share/nginx/html
      - /docker-volumes/data/letsencrypt:/data/letsencrypt
    ports:
      - 80:80
      - 443:443
    depends_on:
      - "server"
      - "redis"

volumes:
  database:
