version: "3.9"

services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile.server
    depends_on:
      - "redis"
    volumes:
      - database:/var/lib/db/
    restart: on-failure

  redis:
    image: redis:alpine
    restart: on-failure

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/apache2/.htpasswd:/etc/apache2/.htpasswd
    ports:
      - 8080:80
    depends_on:
      - "server"
      - "redis"
    restart: on-failure

volumes:
  database:
