# this docker compose file is only to run the backend
version: "3.3"

services:
  server:
    build: 
      context: .
      dockerfile: server.Dockerfile
    ports:
      - 80:8080
    depends_on:
      - "redis"
    volumes:
      - database:/var/lib/db/
    restart: on-failure

  redis:
    image: redis:alpine
    restart: on-failure

volumes:
  database:
